beta_MC: '../inputs/TH2_beta_vs_p_MC_PESI.root'
armenteros: '../inputs/test_v0_builder_520143_armenteros.root'
big_cluster_origin_mc:
  input: '../inputs/BigClusterOriginMC.root'
  drays_energy: True # plot d-rays energy spectrum
  drays_input: '../inputs/MCOriginStudy0208_EkinFix.root'

outdir: '../plots/'
outformat: ['pdf']