beta_MC: '../inputs/TH2_beta_vs_p_MC_PESI.root'
armenteros: '../inputs/test_v0_builder_520143_armenteros.root'
big_cluster_origin_mc:
  input: '../inputs/BigClusterOriginMC.root'
  drays_energy: False # plot d-rays energy spectrum

outdir: '../plots/'
outformat: ['pdf']